language: scala

scala:
  - 2.11.8

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
  - .hoarder-cache
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier

env:
  matrix:
   - scriptName=sbtTests-1.0
   - scriptName=integrationTest
   - scriptName=sbtTests-0.13
   - scriptName=s3-integration

script:
  - echo Will run ci-scripts/scriptName.sh
  - bash ci-scripts/$scriptName.sh

jdk:
  - oraclejdk8
